version: '3.8'
services:
  db:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: avitoSegmentsDb
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data