basePath: /
definitions:
  handlers.errorResponse:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  models.AuthRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  models.CreateSegmentResponse:
    properties:
      id:
        type: integer
    type: object
  models.GetUserSegmentsResponse:
    properties:
      slugs:
        items:
          type: string
        type: array
    type: object
  models.ManageUserToSegmentsRequest:
    properties:
      slugs-to-add:
        items:
          type: string
        type: array
      slugs-to-remove:
        items:
          type: string
        type: array
    required:
    - slugs-to-add
    - slugs-to-remove
    type: object
  models.ManageUserToSegmentsResponse:
    properties:
      slugs-that-have-been-added:
        items:
          type: string
        type: array
      slugs-that-have-been-removed:
        items:
          type: string
        type: array
    type: object
  models.SegmentRequest:
    properties:
      slug:
        type: string
    required:
    - slug
    type: object
  models.SignInResponse:
    properties:
      token:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API server for management users segments
  title: Backend Trainee Assignment 2023 API
  version: "1.0"
paths:
  /auth/sign-in:
    get:
      consumes:
      - application/json
      description: sign in
      operationId: sign-in
      parameters:
      - description: username, password
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SignInResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.errorResponse'
      summary: signIn
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: sign up
      operationId: sign-up
      parameters:
      - description: username, password
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.errorResponse'
      summary: signUp
      tags:
      - auth
  /segment/:
    delete:
      consumes:
      - application/json
      description: delete segment
      operationId: delete-segment
      parameters:
      - description: slug
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.SegmentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: DeleteSegment
      tags:
      - segment
    post:
      consumes:
      - application/json
      description: create segment
      operationId: create-segment
      parameters:
      - description: slug
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.SegmentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CreateSegmentResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: CreateSegment
      tags:
      - segment
  /users-segments/:
    get:
      consumes:
      - application/json
      description: get all user segments
      operationId: get-user-segments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetUserSegmentsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: GetUserSegments
      tags:
      - users-segment
    post:
      consumes:
      - application/json
      description: add and remove segments from user
      operationId: manage-user-to-segments
      parameters:
      - description: slugs to add and remove, user id
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.ManageUserToSegmentsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ManageUserToSegmentsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: ManageUserToSegments
      tags:
      - users-segment
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
